#!/bin/sh

for a in "g++-5" "g++-4.9" "g++-4.8" "g++"; do
    if "$a" "-dumpversion" > /dev/null 2>&1; then
        case "$($a -dumpversion)" in
        5.*)
            echo "$a"
            exit 0
            ;;
        4.[89].*)
            echo "$a"
            exit 0
            ;;
        4.[89])
            echo "$a"
            exit 0
            ;;
        esac
    fi
done
echo "could not find a suitable C++ compiler" >&2
exit 1
